- name: install ad domain services
  win_feature:
    name: AD-Domain-Services
    state: present
- name: install dns
  win_domain: 
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"

#- win_reboot:

- name: configure ad controller
  win_domain_controller:
    state: domain_controller
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
    domain_admin_user: "{{ ad_admin_user }}"
    domain_admin_password: "{{ ansible_password }}"

- name: list domains
  win_command: nltest /dclist:"{{ ad_domain_name }}"
