---
# tasks file for win_service_config
- name: Install packages
  win_chocolatey:
    name: "{{ item }}"
    params: "{{ parameters }}"
    state: present
  with_items: "{{ package_name }}"

- name: enable services
  win_service:
    name: "{{ service_name }}"

- name: setup firewall rule
  win_firewall_rule:
    action: allow
    direction: in
    localport: "{{ local_port }}"
    name: port_22
    protocol: "{{ protocol_name }}"
